POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento",
    "details": "",
    "maximumAttendees": 10
}

###
POST  http://localhost:3333/events/577c0c6a-1046-424c-b867-378b7a1d73bc/attendees
Content-Type: application/json

{
    "name": "gabiela",
    "email": "gabiel@email.com"
}

###
GET http://localhost:3333/events/d31e493a-1faa-4176-a8fc-e2b5df712a88


###
GET http://localhost:3333/attendees/1/badge

###
GET http://localhost:3333/attendees/1/check-in

###
GET http://localhost:3333/events/d31e493a-1faa-4176-a8fc-e2b5df712a88/attendee?query=gabiela